# Generated by Django 4.1 on 2023-10-30 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=50)),
                ('course', models.CharField(max_length=50)),
                ('limitcourse', models.CharField(max_length=50, null=True)),
                ('photo', models.ImageField(upload_to='')),
                ('date', models.DateField()),
            ],
        ),
    ]
