# Generated by Django 4.1 on 2023-11-07 05:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_lectures_delete_lecture'),
    ]

    operations = [
        migrations.CreateModel(
            name='lecture',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('lecturetitle', models.CharField(choices=[('A1', 'AWS Free Tier Account Activation and Enabling AWS Services and Features.'), ('A2', 'Creating a Windows Server 2022 EC2 Instance and Establishing Connectivity Using RDP.'), ('A3', ' Understanding Storage Types and Creating an S3 Bucket with Enabled Features.'), ('A4', 'Creating a Security Group, Adding TCP Rules, and Installing/Publishing an IIS Web Server.'), ('A5', 'Creating a Default VPC, Customizing VPC Settings, and Establishing Peering Between Local and Global VPCs.'), ('A6', 'AWS Identity and Access Management (IAM), User and Group Role-Based Permissions, and Policies.'), ('A7', 'AWS Auto-Scaling and Load Balancing, Application and Network Load Balancing.'), ('A8', 'AWS Virtual Private Network (VPN) for Secure Communication Over the Internet.'), ('A9', 'Configuring and Hosting a Static Website on AWS Cloud with Route 53.'), ('A0', 'Understanding Databases and Establishing Connectivity Between Cloud and On-Premises Environments.')], max_length=2)),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.profile')),
            ],
        ),
        migrations.DeleteModel(
            name='lectures',
        ),
    ]
