# Generated by Django 4.1 on 2023-11-07 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_student_delete_tuple'),
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list', models.CharField(blank=True, choices=[('Module-1: AWS Cloud Feature and Services', 'Module-1: AWS Cloud Feature and Services'), ('Module-2: Amazon Linux | Centos', 'Module-2: Amazon Linux | Centos'), ('MODULE-6: Running Web Applications with Docker Containers (e.g., Nagios or Jenkins) .', 'MODULE-6: Running Web Applications with Docker Containers (e.g., Nagios or Jenkins) .')], max_length=500, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
