# Generated by Django 4.1 on 2023-11-08 14:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0021_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('h_title', models.CharField(choices=[('Module-1: AWS Cloud Feature and Services', 'Module-1: AWS Cloud Feature and Services'), ('Module-2: Amazon Linux | Centos', 'Module-2: Amazon Linux | Centos'), ('Module-3: DevOps methodology', 'Module-3: DevOps methodology'), ('Module-4: Git and GitHub Version Control System', 'Module-4: Git and GitHub Version Control System'), ('Module-5: Jenkins CI/CD Pipeline', 'Module-5: Jenkins CI/CD Pipeline'), ('Module-6: Docker containerization', 'Module-6: Docker containerization'), ('Module-7: Orchestration (Kubernetes)', 'Module-7: Orchestration (Kubernetes)'), ('Module-8: Ansible Automation Configuration Tool', 'Module-8: Ansible Automation Configuration Tool'), ('Module-9: Terraform IAC Tool', 'Module-9: Terraform IAC Tool'), ('Module-10: Grafana Observability and Monitoring', 'Module-10: Grafana Observability and Monitoring')], max_length=1000)),
                ('file', models.FileField(upload_to='files')),
                ('datetime', models.DateTimeField()),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='notes',
        ),
    ]
