# Generated by Django 4.1 on 2023-11-11 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_alter_profile_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='image',
            new_name='photo',
        ),
    ]
