# Generated by Django 5.0.6 on 2024-05-27 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_alter_profile_course_alter_profile_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='limitcourse',
        ),
    ]
